create database orders_food;


create table categories (
  category_id int generated by default as identity primary key,
  category_name varchar(32) not null
);

create table products (
  product_id int generated by default as identity primary key,
  product_name varchar(64) not null,
  category_id int not null references categories(category_id),
  product_price decimal(15, 2) not null,
  product_image varchar(70),
  product_available boolean default true
);

create table tables(
  table_id int generated by default as identity primary key,
  table_number int not null
);





create table users(
  user_id int generated by default as identity primary key,
  role smallint default 0,
  username varchar(40) not null,
  password varchar(64) not null
);

create unique index username_idx on users (lower(username));

CREATE UNIQUE INDEX idx_employees_mobile_phone
ON tables(table_number);

create extension pgcrypto;


create table orders(
  order_id int generated by default as identity primary key,
  order_time timestamp with time zone default current_timestamp,
  order_status smallint default 0,
  table_id int not null references tables(table_id)
);

create table order_item(
  item_id int generated by default as identity primary key,
  item_count int default 1,
  product_id int not null references products (product_id),
  table_id int not null references tables(table_id)
);


select
  t.table_number as user,
  array_agg(oi.item_id) as order_id,
  array_agg(oi.item_count) as count,
  array_agg(p.product_name)as product,
  o.table_id
from
  order_item as oi
join
  products as p on p.product_id = oi.product_id
join 
  tables as t on t.table_id = oi.table_id
join
  orders as o on o.table_id = t.table_id
  where o.order_status = 1
group by
  o.table_id,
  t.table_id
;

insert into order_item(item_count, product_id, table_id) values
(2, 3, 1),
(3, 4, 1),
(1, 21, 1);

insert into order_item(item_count, product_id, table_id) values
(2, 3, 3),
(3, 4, 3),
(1, 21, 3);

insert into orders(table_id) values (1);
insert into orders(table_id) values (3);







/* 
create table orders (
  order_id int generated by default as identity primary key,
  order_time timestamptz default current_timestamp,
  order_product_count smallint default 1,
  product_id int not null references products(product_id),
  table_id int not null references tables(table_id)
); */
/* create table order_products (
	order_product_id int generated by default as identity primary key,
	order_id int not null references orders (order_id),
	product_id int not null references products(product_id),
	order_product_count smallint default 1
); */

